// Generated by CoffeeScript 1.7.1
(function() {
  var async, http, urlOne, urlTwo;

  http = require('http');

  async = require('async');

  urlOne = process.argv[2];

  urlTwo = process.argv[3];

  async.map([urlOne, urlTwo], function(item, done) {
    http.get(item, function(res) {
      var body;
      body = '';
      res.on('data', function(chunk) {
        return body += chunk.toString();
      });
      res.on('end', function() {
        return done(null, body);
      });
    }).on('error', function(err) {
      return done(err);
    });
  }, function(err, results) {
    if (err) {
      console.log(err);
    }
    return console.log(results);
  });

}).call(this);
