// Generated by CoffeeScript 1.7.1
(function() {
  var async, hostname, http, port, url;

  hostname = process.argv[2];

  port = process.argv[3];

  url = "http://" + hostname + ":" + port;

  http = require('http');

  async = require('async');

  async.series({
    post: function(done) {
      var _createUser;
      _createUser = function(userID, cb) {
        var jsonData, opts, req;
        opts = {
          port: port,
          hostname: hostname,
          path: '/users/create',
          method: 'POST'
        };
        jsonData = JSON.stringify({
          user_id: userID
        });
        req = http.request(opts, function(res) {
          res.on('data', function(chunk) {});
          res.on('end', function() {
            return cb();
          });
        });
        req.on('error', cb);
        req.write(jsonData);
        req.end();
      };
      async.times(5, function(n, next) {
        _createUser(++n, function(err) {
          return next(err);
        });
      }, function(err) {
        if (err) {
          return done(err);
        }
        return done(null, 'saved');
      });
    },
    get: function(done) {
      http.get(url, function(res) {
        var body;
        body = '';
        res.on('data', function(chunk) {
          return body += chunk.toString();
        });
        res.on('end', function() {
          return done(null, body);
        });
      }).on('error', function(e) {
        return done(err);
      });
    }
  }, function(err, results) {
    if (err) {
      console.log(err);
    }
    return console.log(results);
  });

}).call(this);
