// Generated by CoffeeScript 1.7.1
(function() {
  var actualBody, async, count, http, url;

  url = process.argv[2];

  http = require('http');

  async = require('async');

  actualBody = '';

  count = 0;

  async.whilst(function() {
    return actualBody !== 'meerkat';
  }, function(done) {
    var body;
    body = '';
    http.get(url, function(res) {
      res.on('data', function(chunk) {
        return body += chunk.toString();
      });
      res.on('end', function() {
        count++;
        actualBody = body;
        return done();
      });
    }).on('error', done);
  }, function(err) {
    if (err) {
      console.log(err);
    }
    return console.log(count);
  });

}).call(this);
